### ISSUE TITLE
Create docs view on Community Roadmap with CTAs

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/docs.openedx.org#145]
The Open edX Community Roadmap should contain a course-level (epic/initiative level) view of the docs.openedx.org project. It should provide a bird's eye view of the strategic goals and milestones of the documentation overhaul, as well as provide community easy entrypoint to get involved. It should also link to the docs.openedx.org Project Board, which is meant to house fine-grained issues.

- [ ] Create template CTA epic issue
- [ ] Define standard approach for getting candidate authors the info they need - examples, templates
- [ ] Dedupe backlog - looks like some dupes pulled over from cleanse of empty content

**Comment by sarina** [comment]
I'm not sure how to integrate this feedback into our current docs systems. Any thoughts?
