### ISSUE TITLE
Start Accepting Contributions to the new Docs Site

### ISSUE THREAD

**Issue by feanil** [openedx/docs.openedx.org#16]
Below is the list of tasks that need to be accomplished before we can begin accepting contributions to this repo from anyone in the community.  Once these tasks are done we can announce more widely that the repo is ready to accept contributions.

- [x] #18
- [x] #19
- [x] Publish this repo to https://docs.openedx.org and keep in sync with master.
- [x] Setup the repo to take contributions
  - [x] Ensure the CLA check is setup and running.
  - [x] Require successfull doc builds before merging PRs
  - [x] Require PRs for changes to main branch.
  - [x] Add an openedx.yml

**Comment by feanil** [comment]
Everything outlined here is now done, I think we're ready to start accepting new contributions.
