### ISSUE TITLE
i18n Support For Documentation

### ISSUE THREAD

**Issue by feanil** [openedx/docs.openedx.org#874]
To expand access to the Open edX platform, we'd like to have all the relevant documentation also be translated.  Because the master version of documentation can be more volatile, we would instead like to maintain translated versions of named releases.

AC:
- [ ] openedx/edx-documentation#2029
- [ ] openedx/edx-documentation#2026
- [ ] openedx/edx-documentation#2027
- [ ] openedx/edx-documentation#2028
